### ISSUE TITLE
起動できないです

### ISSUE THREAD

**Issue by RIVAIVU** [togenyan/Yo-kai_Editor_B2#12]
this application failed to start because it could not find or load
the Qt platform plugin “Windows”
in””.

Available platform plugin are:windows.

Reinstalling the application may fix this problem.

これが出るのですが何が原因なのでしょうか?
Visual Studio 2017 の Microsoft Visual C++ 再頒布可能パッケージは入れてあります。

**Comment by RIVAIVU** [comment]
一番初期のB2のエディター以外全部これが出て開けないです。

**Comment by togenyan** [comment]
何だかやっかいそうです。

｢Visual Studio 2017 の Microsoft Visual C++ 再頒布可能パッケージ｣のうち、x86のほうをインストールして再度試してもらえますか?

**Comment by RIVAIVU** [comment]
それいれてます。

**Comment by RIVAIVU** [comment]
何で初期だけ開けるんでしょうか?

**Comment by togenyan** [comment]
> それいれてます。

x86 と x64 両方入れてもだめですか?
どうしても駄目ならVisual Studio 2017を入れてしまうという手もありますが…

> 何で初期だけ開けるんでしょうか?

ビルド環境が変わったからでしょう。ソースコードの変更で動かなくなったとは考えにくいです。
v0.1は MSVC 2013/Qt 5.5 でビルドしてあります。以降のバージョンもその古い環境でビルドすれば動くと思いますが、もうその環境は破棄してしまったので手元にはありません。

OSのバージョンと64ビット版か否か、を教えてください。
なお、Windows向けのバイナリの動作確認は Windows 10 Pro 64bit で行っています。

**Comment by RIVAIVU** [comment]
Windows vistaの32bitです。

**Comment by togenyan** [comment]
原因はOSが古いことのようですね。Qt5.7以降ではVista以前はサポートされません。
https://wiki.qt.io/PlatformSupport
他により新しいパソコンがあれば、それを使ってください。または、OSをアップデートすることをおすすめします。
どうしてもできないというのであれば、お知らせください。

**Comment by RIVAIVU** [comment]
僕のＰＣは古いのでUpdateできないです・・・・。

**Comment by togenyan** [comment]
Qt5.6.3でビルドしてみました。どうですか?
[Yo-kai Editor B2 Windows.zip](https://github.com/togenyan/Yo-kai_Editor_B2/files/1608361/Yo-kai.Editor.B2.Windows.zip)

メモ:
* QHexEditの要件から、利用できるQtは5.6以降
* 他のソースは（5.10向けのつもりだったが）変更なしで5.6でビルドできる
* コンパイラはMSVC 2017を2015として設定し使用

**Comment by RIVAIVU** [comment]
できました！！本当にありがとうございます！！

**Comment by togenyan** [comment]
解決したようで何よりです。これからはQt 5.6.3でビルドすることにします。
