### ISSUE TITLE
どのファイルをクリックしてツールを開くのですか？

### ISSUE THREAD

**Issue by RaghavBro** [togenyan/Yo-kai_Editor_B2#13]
So I have downloaded the zip file on my laptop but I don't know which file is the tool so can you guys tell me which on it it??

だから私は私のデスクトップにzipファイルをダウンロードしたが、私はどのファイルがツールであるかわからない。だからあなたは私にどのファイルを開くか教えてもらえますか？

**Comment by togenyan** [comment]
The executable file is "Yo-kai Editor B2.exe" (on Windows) or "Yo-kai Editor B2.app" (on OS X. To be accurate it's an app bundle but it *surely* works).

Have you downloaded the release binaries? The executable is not included in the source code archive.
https://github.com/togenyan/Yo-kai_Editor_B2/releases

**Comment by RaghavBro** [comment]
Thanks I actually didn't downloaded that and thanks for the response
