### ISSUE TITLE
Stones for the unlockable dungeons

### ISSUE THREAD

**Issue by rece225** [togenyan/Yo-kai_Editor_B2#14]
Are all the stones available in the editor? I wanna try the dungeons to unlock the new enma's and new crystal shogunyan, please put them in the editor if the code is already released :) if not can you explain me how and when they'll be releasing them? HUGE THANKS FOR ALL YOUR HARD WORK!!!

**Comment by Fillerfx** [comment]
All the stones are already avaliable in the editor, you can edit your infinite stones in the "key items" tab (I wouldnt reccomend messing with the key items tho) you can also get the infinite stone fragments in the "items" tab, you will have to know a bit of japanese to tell which is which but all of the fragments have an "1" and "2" at the end.

**Comment by rece225** [comment]
Yup I found it.
