### ISSUE TITLE
Not possible to edit/add items

### ISSUE THREAD

**Issue by mogurinyan** [togenyan/Yo-kai_Editor_B2#3]
I was trying to add items ,such as coins, and edit their quantity in the 'items' section of the new 0.2 ver editor, but even though I am clicking 'apply' the changes do not stay.  Thanks for your work.

**Comment by togenyan** [comment]
Try the following steps:
1. Choose desired item in the "TYPE" combobox.
2. Set the QTY as desired.
3. Click the "STACKABLE" flag checkbox to check it.
4. Click the "Auto-number" button (exact name depends on your OS's locale)
5. Click the apply button.

If the issue persists, please let me know your OS and send me your save data via email or as a attachement on GitHub.

**Comment by ShadowCaptain22** [comment]
Seriously the same thing happens to me, when I modify / create a yokai by giving it to (apply) the changes do not load me, the same with the money oni, the medallium, the objects. I had to use version 0.1 to be able to modify the yokai
Please check it and fix it

**Comment by mogurinyan** [comment]
I've tried all those steps and the issue still persists. My OS is Windows 10 Pro. And I've sent you my save data via email. Thank you so much.

**Comment by mogurinyan** [comment]
As for what ShadowCaptain22 said above, I am not experiencing any issues editing/modifying Youkai. My issue is only with items.

**Comment by mogurinyan** [comment]
Sorry for multiple posting, I have also checked that editing the gasha crank-a-kai  does not work either. Although in the editor it says I've set it to 99, once I load the edited save in game I still have got 3/3, as if it hadn't been modified. Sorry for bothering you and thank you for taking your time to do all this.

**Comment by togenyan** [comment]
I confirmed the bug happens on Windows build. Until it gets fixed, use v0.1.
