### ISSUE TITLE
妖怪・アイテムの変更が反映されない (Windows版)

### ISSUE THREAD

**Issue by shigerukk** [togenyan/Yo-kai_Editor_B2#4]
お忙しい中　ツールの更新ありがとうございました。
早速　ダウンロードし、起動しました。
非常に沢山の項目が追加・見直しされて本当にありがとうございます。

OS　WIN10ですが、他の方もご質問されておりましたが、記載いただきました手順通りに操作いたしましたが、適用ボタンを押下しても反映されない症状が発生しております。（妖怪・アイテムの追加だけでなく、単なる変更でも適用ボタンを押下しても反映されない状態となっております。）

また、妖怪辞典・鬼玉・ガチャ回数なども試してみましたが、チェック→適用ボタン→保存しても反映されず、一旦終了して再度同ファイルを開くと保存前の状態（＝保存が反映されない）となっております。

**Comment by togenyan** [comment]
dup of #3
