### ISSUE TITLE
version 0.2.1 の更新ありがとうございました

### ISSUE THREAD

**Issue by shigerukk** [togenyan/Yo-kai_Editor_B2#5]
version 0.2.1 の更新ありがとうございました。
早速試してみました。
妖怪の追加はまだ時間がないため試しておりませんが、その他は以下の点を除いてほぼ自分が作成したかったセーブデータが作成できました本当にありがとうございます。

お時間ができまして、次回更新の際に以下の点の見直しをいただければ幸いです。当方の使用誤りでしたら申し訳ございません。

１．そうびですが、追加できましたのですが、ゲームデータ上の「もっているかずが０」と表示されてしまい、ゲーム上で一旦バトルアイテムBOXへ移動後、再度アイテムBOXへ移動すると正常に「１」と表示されました。
→　併せて、可能あればそうびのもっているかずが変更できるような入力BOX新設いただけると嬉しいです。

２．一部のどうぐがだいじなものに分類をされております。「だいじなもの」の種類ボタンを押下した時に、リストが途中で空欄となり、その下に表示されているアイテムが「どうぐ」ではないかと思われます。
例）青鬼メダル　等

３．最後に単なる希望ですが、可能であれば、バトルアイテム・そうび・どうぐを追加する際に、「全アイテム９９」追加されるようなボタン・チェックＢＯＸを作成いただけると非常にありがたいです。
→　とくに今回どうぐの数が非常に多く１つ１つ追加するのにだいぶ時間がかかりましたので、そのような便利な機能の実装をいただけると本当にありがたいです。

その他　妖怪辞典開放・ガチャ回数変更・鬼玉変更すべて反映しました！
ありがとうございました。

**Comment by UMRtilyan** [comment]
新しいバージョンありがとうございます。
妖怪大辞典でおいて、妖怪コンプリートになってましたが、
ともだち手帳にのっている大辞典が44種になっています。修正おねがいします。

**Comment by togenyan** [comment]
動作検証いただきありがとうございます。

1.  そうびの所持数は、バージョン0.2.2で編集できるようになりました。
（スタックできないので1以外の値は意味がないと思われます）

2. ゲームの内部データではそうなっています。空白以降のアイテムは未使用アイテムではないでしょうか。
「青鬼メダル」などのアイテムが「だいじなもの」でないのは確かですか?

3. バージョン0.2.2で、各種タブに全ての項目を追加するボタンを実装しました。
なお、個数は設定されませんが、複数項目の一括編集で簡単に設定できます。

**Comment by shigerukk** [comment]
１．スタックできないことを知りませんでした。勉強不足で申し訳ございませんでした。
２．当方の間違いでご指摘の通り「だいじなもの」でした
３．１つ１つ追加しておりましたので、本当に助かりました。ありがとうございます。
追加したアイテムとリストのアイテムの数があわずに追加が漏れてしまったものを探すのに非常に苦労したので実装いただきまして本当に助かりました。
