### ISSUE TITLE
大辞典のメダルの最大数について

### ISSUE THREAD

**Issue by hisa020507** [togenyan/Yo-kai_Editor_B2#7]
いつもありがとうございます。

大辞典のメダルの最大数について、766体登録後みてみると、766/730や766/732となり、端数の妖怪が表示されません。

何か解決方法はございますでしょうか？

よろしくお願い致します。

**Comment by hisa020507** [comment]
すみません、自己解決いたしました。
申し訳ございません。

**Comment by shigerukk** [comment]
当方は登録数／510でツールの予約された大辞典の枠数２５５より大きな数字が入力できないため、表示されない状態となっております。
そのように自己解決なされたのかご教示いただけると助かります。
よろしくお願いいたします。

**Comment by hisa020507** [comment]
当方の分母は730ほどでしたので参考になるかは分からないですが、
タブ「情報1」の「予約された大辞典の枠の数」を0にすると766枠全て解放されました。

**Comment by shigerukk** [comment]
hisa020507 様
お忙しい中　メッセージいただきましてありがとうございました。
教えていただいた通り操作したら当方も７６６枠に全て解放されました。
本当にありがとうございました。
